### PR TITLE
Expose arguments as an object

### PR DESCRIPTION
**Pull request by tayler-king**
This allows you to do

```js
ce({
    color: '',
    author: '',
    ...
    images: ''
});
```

See example:

```js
const test = ({a, b}) => {
    console.log(`a: ${a}\nb: ${b}`);
};

test({ a: 'one', b: 'two' });
> a: one
> b: two
```

### CODE REVIEW

**Comment by FireController1847** [comment]
@Kondax That would defeat the purpose, though, as default embeds are made with an object. If you're going to go this far, you might as well go straight back to the default embeds like the below:
```javascript
m.channel.send({embed:{
  "color": 0xFFFFFF,
  "title': "Sup"
}});
```

**Comment by tayler-king** [comment]
So what benefit does this package offer? I don't work with Discord.js - just curious.

**Comment by FireController1847** [comment]
It just allows users to quickly create an embed without having to format it like an object. It just makes the process a lot quicker and more compact. Of course, there is still a time and a place to use objects.

**Comment by tayler-king** [comment]
Seems really counter-intuitive to me but each to their own.

**Comment by FireController1847** [comment]
:P

**Pull request closed without merging**
